// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBj20GATatdhbwDo_w7tUUx1pwIk4dox6g',
    appId: '1:512712190568:web:749617769004527f6ea9dd',
    messagingSenderId: '512712190568',
    projectId: 'tradeloop-baf12',
    authDomain: 'tradeloop-baf12.firebaseapp.com',
    storageBucket: 'tradeloop-baf12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA575ITdIuzVY4P5qLzjmOOr3CXSqrQMQ',
    appId: '1:512712190568:android:f5e65ccd9af8862d6ea9dd',
    messagingSenderId: '512712190568',
    projectId: 'tradeloop-baf12',
    storageBucket: 'tradeloop-baf12.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBj20GATatdhbwDo_w7tUUx1pwIk4dox6g',
    appId: '1:512712190568:web:aa6bd2cef7fff7e06ea9dd',
    messagingSenderId: '512712190568',
    projectId: 'tradeloop-baf12',
    authDomain: 'tradeloop-baf12.firebaseapp.com',
    storageBucket: 'tradeloop-baf12.appspot.com',
  );
}
